CREATE TABLE bikes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bike_name TEXT NOT NULL,
    bike_description TEXT NOT NULL,
    bike_category TEXT NOT NULL,
    bike_image TEXT NOT NULL
);